# jQuery behavior
# Base dependance
jquery:
  javascripts: [ jquery/jquery-1.2.6 ]


# Cookie behavior
# Manages cookies via javascript
cookie:
  depends_on:  [ jquery ]
  javascripts: [ jquery/plugin/cookie ]


# Box behavior
# Javascript hover box
box:
  compilation: copy
  depends_on:  [ jquery ]
  javascripts: [ jquery/plugin/box ]
  stylesheets: [ box ]
  scripts:
    _auto: $('a[rel*=box]').filter('a :not(.has-box)').box().addClass('has-box');

# Links behavior
# Create unobstrusive ajax links
links:
  depends_on:  [ jquery, loader ]
  javascripts: [ jquery/plugin/links ]
  scripts:
    _auto: $.links();

# Loader behavior
# Little "please wait while loading" centered div to use during ajax requests
loader:
  depends_on:  [ jquery ]
  stylesheets: [ loader ]
  scripts:
    _auto:  |
      if ( 0 == $('div.sf_ajax_loader').length )
      {
        $('body').append('<div class="sf_ajax_loader"><img src="/images/loading.gif" alt="" />Chargement en cours...<img src="/images/loading.gif" alt="" /><'+'/div>');

        $(document).ajaxSend(function() {
          $('div.sf_ajax_loader').show();
        });

        $(document).ajaxStop(function() {
          setTimeout(function() { $('div.sf_ajax_loader').hide(); }, 250);
        });
      }
      else
      {
        setTimeout(function() { $('div.sf_ajax_loader').hide(); }, 250);
      }

redirect:
  scripts:
    go:
      template:
        window.location = '<<url>>';

# Simple tooltip - currently being converted to jquery
tooltip:
  depends_on:  [ jquery ]
  javascripts: [ simple/tooltip ]
  stylesheets: [ tooltip ]
  class:       sfJavascriptTooltipBehavior

clickmenu:
  depends_on:  [ jquery ]
  javascripts: [ jquery/plugin/clickmenu ]
  stylesheets: [ clickmenu ]

# Animation behavior
# For now, only shake is available
animation:
  depends_on:  [ jquery ]
  javascripts: [ jquery/plugin/animation ]

# Treeview plugin
treeview:
  depends_on:  [ jquery, cookie ]
  javascripts: [ jquery/plugin/treeview ]
  stylesheets: [ treeview ]

# Focus plugin - under development, no good
#
# focus:
#   depends_on:  [ jquery ]
#   javascripts: [ "%sf_behavior_dir%/jquery-plugin/focus" ]

# Accessible hover menu
hovermenu:
  depends_on:  [ jquery ]
  javascripts: [ jquery/plugin/hovermenu ]

# «selectboxes»  plugin interface (comes from official plugin repository)
selectboxes:
  depends_on:  [ jquery ]
  javascripts: [ jquery/plugin/selectboxes/jquery.selectboxes ]

# «form» jQuery plugin interface (comes from official plugin jQuery repository)
form:
  depends_on:  [ jquery, loader ]
  javascripts: [ jquery/plugin/form/jquery.form ]
  scripts:
    ajaxify:
      template:  |
        $(document).ready(function() {
          var options = {
            target: '<<target>>'
          };
          $('form#<<formId>>').ajaxForm(options);
        });
# Form observer behavior
    observe:
      template: |
        $(document).ready(function() {
          $('<<target>>').change(function(){ $('<<update>>').load('<<url>>', {value: $(this).val()}); });
        });

# «scrollTo» jQuery plugin interface (comes from official plugin jQuery repository)
scrollto:
  depends_on: [ jquery ]
  javascripts: [ jquery/plugin/scrollto/jquery.scrollTo ]


# jQuery Effects
effectCore:
  depends_on:  [ jquery ]
  javascripts: [ jquery/ui/effects.core ]
effectBlind:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.blind ]
effectBounce:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.bounce ]
effectClip:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.clip ]
effectDrop:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.drop ]
effectExplode:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.explode ]
effectFold:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.fold ]
effectHighlight:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.highlight ]
effectPulsate:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.pulsate ]
effectScale:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.scale ]
effectShake:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.shake ]
effectSlide:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.slide ]
effectTransfer:
  depends_on:  [ effectCore ]
  javascripts: [ jquery/ui/effects.transfer ]


# jQuery UI
uiCore:
  depends_on:  [ jquery ]
  javascripts: [ jquery/ui/ui.core ]
uiAccordion:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.accordion ]
uiDatePicker:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.datepicker, jquery/ui/i18n/ui.datepicker-fr ]
  stylesheets: [ themes/default/ui.datepicker ]
uiDialog:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.dialog ]
uiDraggable:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.draggable ]
uiDroppable:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.droppable ]
uiResizable:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.resizable ]
uiSelectable:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.selectable ]
uiSlider:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.slider ]
uiSortable:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.sortable ]
uiTabs:
  depends_on:  [ uiCore ]
  javascripts: [ jquery/ui/ui.tabs ]

